### ISSUE TITLE
Fatal error when running addfield.php

### ISSUE THREAD

**Issue by lucky-naty** [radus28/wooti#2]
When I'm running addfield.php I get this errors. Can you help resolve it?
Warning: include_once(../config.inc.php): failed to open stream: No such file or directory in /var/www/www-root/data/www/myCRM.com/woo28/wooti-master/addfield.php on line 6

Warning: include_once(): Failed opening '../config.inc.php' for inclusion (include_path='.:') in /var/www/www-root/data/www/myCRM.com/woo28/wooti-master/addfield.php on line 6

Notice: Undefined variable: root_directory in /var/www/www-root/data/www/myCRM.com/woo28/wooti-master/addfield.php on line 7

Warning: include_once(vtlib/Vtiger/Module.php): failed to open stream: No such file or directory in /var/www/www-root/data/www/myCRM.com/woo28/wooti-master/addfield.php on line 8

Warning: include_once(): Failed opening 'vtlib/Vtiger/Module.php' for inclusion (include_path='.:') in /var/www/www-root/data/www/myCRM.com/woo28/wooti-master/addfield.php on line 8

Warning: include_once(vtlib/Vtiger/Block.php): failed to open stream: No such file or directory in /var/www/www-root/data/www/myCRM.com/woo28/wooti-master/addfield.php on line 9

Warning: include_once(): Failed opening 'vtlib/Vtiger/Block.php' for inclusion (include_path='.:') in /var/www/www-root/data/www/myCRM.com/woo28/wooti-master/addfield.php on line 9

Fatal error: Uncaught Error: Class 'Vtiger_Module' not found in /var/www/www-root/data/www/myCRM.com/woo28/wooti-master/addfield.php:11 Stack trace: #0 {main} thrown in /var/www/www-root/data/www/myCRM.com/woo28/wooti-master/addfield.php on line 11

**Comment by lucky-naty** [comment]
Resolved
instead of this
include_once('../config.inc.php');
set_include_path($root_directory);
include_once('vtlib/Vtiger/Module.php');
include_once('vtlib/Vtiger/Block.php');

I wrote the full path in both files addfield.php and  registecf.php
include_once('/var/www/www-root/data/www/myCRM.com/config.inc.php');
set_include_path($root_directory);
include_once('/var/www/www-root/data/www/myCRM.com/vtlib/Vtiger/Module.php');
include_once('/var/www/www-root/data/www/myCRM.com/vtlib/Vtiger/Block.php');

And it worked!

**Comment by ajstharsan-radus28** [comment]
@lucky-naty  closing as problem was solved. Thanks
