### ISSUE TITLE
Error: No Client found by email-{"success":false,"error":{"code":"ACCESS_DENIED","message":"Permission to perform the operation is denied"}}

### ISSUE THREAD

**Issue by lucky-naty** [radus28/wooti#3]
Woocommerce webhook sends well, but nothing happenung in crm and I'm getting this error
No Client found by email-{"success":false,"error":{"code":"ACCESS_DENIED","message":"Permission to perform the operation is denied"}}

**Comment by ajstharsan-radus28** [comment]
> Woocommerce webhook sends well, but nothing happenung in crm and I'm getting this error
> No Client found by email-{"success":false,"error":{"code":"ACCESS_DENIED","message":"Permission to perform the operation is deni

Hi ! sorry for late reply.  Are you still having the problem or solved?  This error may be due to something wrong at vtiger side. Example, the module you are trying to connect is disabled.

**Comment by ajstharsan-radus28** [comment]
@lucky-naty  I accidentally closed the issue.

**Comment by ajstharsan-radus28** [comment]
Closing as no reply
